ALTER TABLE daily_records
  ADD COLUMN IF NOT EXISTS interphone_only INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS paper_presentation INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS full_talk INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS indoor_entry INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS prospects INTEGER NOT NULL DEFAULT 0;
