ALTER TABLE contracts
  ADD COLUMN IF NOT EXISTS option_removed  BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS landline_removed BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS router_removed  BOOLEAN NOT NULL DEFAULT FALSE;
