ALTER TABLE contracts
  ADD COLUMN IF NOT EXISTS needs_option_removal   BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS needs_landline_removal BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS needs_router_removal   BOOLEAN NOT NULL DEFAULT FALSE;
