ALTER TABLE daily_reports
  ADD COLUMN IF NOT EXISTS visits          INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS net_meetings    INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS owner_meetings  INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS negotiations    INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS acquisitions    INTEGER NOT NULL DEFAULT 0;
